--- 
- name: Provision Environment
  hosts: workstation
  gather_facts: no
  tasks:
    - name: Provision Workstation
      include_role: 
        name: bsio.iac.roles.provision_workstation
        tasks_from: provision_workstation
    
    - name: Provision Staging Servers
      include_role: 
        name: bsio.iac.roles.provision_staging_servers
        tasks_from: provision_staging_servers        
