--- 
- name: Provision Environment
  hosts: workstation
  gather_facts: no
  tasks:
    - name: Install Hyper-V Feature
      include_role: 
        name: bsio.iac.roles.provision_workstation
        tasks_from: provision_workstation