--- 
- name: Provision Environment
  hosts: workstation
  gather_facts: no
  tasks:
    - name: Install Hyper-V Feature
      include_role: 
        name: bsio.iac.roles.hyper_v
        tasks_from: install-hyper-v